name: Manual run web tests
run-name: on manual - ${{ github.actor }} is testing web tests runner with rf and playwright
on: 
  workflow_dispatch:
    inputs: 
      browser:
        type: string
        description: Informe o browser
        required: true
      
jobs:
    web-tests:
        runs-on: ubuntu-latest
        permissions: write-all

        steps:
            - name: Checkout
              uses: actions/checkout@v3
        
            - name: Install Python
              uses: actions/setup-python@v4 
              with: 
                python-version: '3.10'

            - name: Install Node.js 19.1
              uses: actions/setup-node@v3
              with:
                node-version: '19.1'

            - name: Install Requirements
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                sudo npm install @playwright/test
                sudo npx playwright install-deps
                rfbrowser init

            - name: Run Robot Framework Web Tests
              run: |
                 robot -d ./results -v HEADLESS:true -v BROWSER:${{ inputs.browser }} tests

            - name: Upload test results
              if: always()
              uses: actions/upload-artifact@v3
              with:
                name: results-${{ inputs.browser }}
                path: ./results
                if-no-files-found: ignore
                retention-days: 2 

            - name: Download tests results
              if: always()
              uses: actions/download-artifact@v1
              with:
                name: results-${{ inputs.browser }}

            - name: Send report
              if: always()
              uses: joonvena/robotframework-reporter-action@v2.1
              with:
                report_path: results-${{ inputs.browser }}
                gh_access_token: ${{ secrets.GITHUB_TOKEN }}
                show_passed_tests: false

            





            